### ISSUE TITLE
cannot upload .tar file

### ISSUE THREAD

**Issue by WenmuZhou** [lorenzodifuccia/http.server#2]
when I choice a x.tar file to upload, it show this
![image](https://user-images.githubusercontent.com/12406017/198639118-b2961cca-b1f1-4922-97c6-a1764694c765.png)

**Comment by lorenzodifuccia** [comment]
Hi @WenmuZhou, I'll investigate. Thanks for the support! 💪🏻

**Comment by lorenzodifuccia** [comment]
What was the problem?
